In [27]:
import torch
import numpy as np

In [139]:
# basic
torch.tensor([4, 5, 6])
torch.from_numpy(np.array([7, 8, 9]))
torch.zeros(8, 8)
torch.ones(3, 8)
torch.randn(3, 8)
torch.randint(0, 21, (8, 8))
torch.rand(8, 8)
torch.randperm(8)
torch.eye(8)
torch.full((2, 4), 8)
torch.empty(2, 4)
torch.arange(0, 10, 3)
torch.linspace(0, 9, 9)
x = torch.randn(2, 3)
y = torch.randn(2, 3)
x * y
x / y
x ** 2
x % 2
x.add_(1)
torch.mm(x, y.t()) # 2d
torch.matmul(x, y.t())
m = torch.randn(2, 3, 4)
n = torch.randn(2, 4, 3)
torch.matmul(m, n)
x @ y.t()
torch.bmm(m, n) # 3d
x = torch.randn(2, 1)
y = torch.randn(1, 2)

x = torch.tensor([1, 2])  # 1D 张量 (2,)
y = torch.tensor([3, 4])  # 1D 张量 (2,)
y_t = y.t()  # 1D 转置仍为 (2,)

torch.einsum('i,j->ij', x, y_t)
# # like
# x = torch.randint(0, 3, (2, 3, 4))
# torch.zeros_like(x)
# torch.rand_like(x)

# math
x = torch.randint(0, 3, (2, 3, 4))
torch.abs(x)
torch.sqrt(abs(x))
torch.exp(x)
torch.log(x.abs() + 1e-10)
torch.sin(x)
torch.cos(x)
torch.sigmoid(x)
torch.tanh(x)
torch.clamp(x, min=0, max=1)
torch.clip(x, 0, 1)
torch.round(x)
torch.floor(x)
torch.ceil(x)

x.prod()
x.sum()
x
x.sum(dim=1)
x.sum(dim=1, keepdim=True)
print(x)
x.max(dim=1)
x.cumsum(dim=1)
x.cumsum(dim=2)
x.argmax(dim=1)
torch.median(x)
torch.topk(x, 3, dim=1)
torch.sort(x, dim=1)
torch.where(x > 0, 999, torch.zeros_like(x))

tensor([[[1, 2, 2, 1],
         [2, 2, 2, 2],
         [2, 0, 1, 1]],

        [[2, 1, 2, 1],
         [0, 1, 1, 0],
         [2, 1, 1, 0]]])


tensor([[[999, 999, 999, 999],
         [999, 999, 999, 999],
         [999,   0, 999, 999]],

        [[999, 999, 999, 999],
         [  0, 999, 999,   0],
         [999, 999, 999,   0]]])

In [40]:
# core properties
x = torch.randn(2, 3, 4)
x.shape
x.dim()
x.numel()
x.dtype
x.device
x.requires_grad

False

In [ ]:
# shape
x = torch.randn(2, 3, 4)
x.view(2, 12)
x.reshape(2, 12)
x.view(-1)
x.flatten()
x.flatten(1)

# add dim
x.unsqueeze(0)
x.unsqueeze(-1)
m = x.transpose(0, 1).contiguous()
n = x.transpose(0, 1)
x.transpose(0, 1)
x.permute(2, 0, 1)

print(x)

torch.cat([x, x], dim=0)
torch.stack([x, x], dim=0)
torch.split(x, 2, dim=2)
torch.chunk(x, 2, dim=2)

torch.repeat_interleave(x, 3, dim=0)
x.expand(2, 3, 4)
x.repeat(2, 3, 1)

tensor([[[ 0.8046,  0.9434, -0.9488,  0.3731],
         [ 0.4768, -0.2819,  1.1088, -0.2260],
         [-0.0728,  2.1800,  0.1333,  0.5033]],

        [[ 0.6066,  0.5870, -1.1039,  0.8438],
         [-0.8987,  0.3118,  0.8699, -0.2911],
         [-0.8762, -0.0764,  1.1834,  0.1131]]])


tensor([[[ 0.8046,  0.9434, -0.9488,  0.3731],
         [ 0.4768, -0.2819,  1.1088, -0.2260],
         [-0.0728,  2.1800,  0.1333,  0.5033],
         [ 0.8046,  0.9434, -0.9488,  0.3731],
         [ 0.4768, -0.2819,  1.1088, -0.2260],
         [-0.0728,  2.1800,  0.1333,  0.5033],
         [ 0.8046,  0.9434, -0.9488,  0.3731],
         [ 0.4768, -0.2819,  1.1088, -0.2260],
         [-0.0728,  2.1800,  0.1333,  0.5033]],

        [[ 0.6066,  0.5870, -1.1039,  0.8438],
         [-0.8987,  0.3118,  0.8699, -0.2911],
         [-0.8762, -0.0764,  1.1834,  0.1131],
         [ 0.6066,  0.5870, -1.1039,  0.8438],
         [-0.8987,  0.3118,  0.8699, -0.2911],
         [-0.8762, -0.0764,  1.1834,  0.1131],
         [ 0.6066,  0.5870, -1.1039,  0.8438],
         [-0.8987,  0.3118,  0.8699, -0.2911],
         [-0.8762, -0.0764,  1.1834,  0.1131]],

        [[ 0.8046,  0.9434, -0.9488,  0.3731],
         [ 0.4768, -0.2819,  1.1088, -0.2260],
         [-0.0728,  2.1800,  0.1333,  0.5033],
         

In [56]:
# transform
x = torch.randn(3, 4, 5)
x.int()
x.long()
x.float()
x.double()
x.half()
x.bool()
x.to(torch.int32)

# device
# x.cuda()
# x.to('cuda:0)
x.cpu()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x.to(device)

tensor([[[ 0.7402,  1.9651, -1.5312, -0.7930,  0.9341],
         [-0.5728,  0.2285,  0.3958, -0.0130, -0.8526],
         [-0.3905,  0.8087, -1.2173, -0.6669,  0.2288],
         [ 0.0664, -0.7387,  0.1284, -0.5602, -0.2608]],

        [[ 0.7837,  0.1825,  0.1997,  0.6498,  1.7486],
         [-0.4840, -0.1382,  0.9988, -0.3013,  1.1092],
         [-1.2053, -1.3156, -0.6011,  0.0480, -1.6663],
         [-0.0547, -0.7900, -0.5167,  1.6236,  0.9342]],

        [[-2.1420,  0.4545, -0.2534,  0.2482, -0.4428],
         [-0.2880, -0.5616, -0.8953,  0.5639, -0.3590],
         [ 0.3355, -0.8704, -1.0210, -2.1102, -0.1744],
         [ 0.2264, -0.6930, -0.4195, -0.0839, -0.5192]]])

In [ ]:
# 索引 indexing
# 切片 slicing
x = torch.randn(4, 5, 6)
print(x)
x[0]
x[:2]
x[1, :, 3]
x[..., 0]
x[:, 0, :]
x[0, :, :]
x[:, :, 0]

tensor([[[ 1.0652, -0.2533,  0.9170, -0.7959, -0.5045,  0.1685],
         [ 1.8945,  0.4327, -2.5662, -0.5106,  1.6490, -1.1339],
         [-0.2611, -0.9185, -1.5674,  1.3769,  0.5577,  0.2158],
         [-0.3005,  0.6127, -0.1388,  0.2547,  1.2757,  0.3722],
         [ 1.4643, -0.9996,  0.8162,  0.4761,  0.1240, -0.2115]],

        [[ 0.4498, -0.3081, -0.1387,  0.6527,  1.8462,  0.8729],
         [ 0.1772, -0.4845, -1.1760, -1.0828, -0.1822,  0.3550],
         [ 1.0757,  0.5844,  0.3320,  0.7014, -1.5299,  1.0265],
         [ 0.1302, -0.3371, -0.3607,  1.2070, -0.2084, -0.3488],
         [ 0.5626, -0.2643, -0.2643, -0.4714,  0.1122,  0.2665]],

        [[-0.1850, -0.5589, -1.4095,  0.2071,  0.4605,  0.8251],
         [ 0.1699,  0.1108, -0.3817, -0.2245, -0.3563,  0.5686],
         [-1.4455,  1.4435, -0.5477, -0.8545, -1.0943, -1.1530],
         [ 1.4274, -2.0076,  1.5345, -2.2431, -1.6794,  1.3923],
         [-1.0439,  1.4954, -0.0311,  0.5872, -0.1888, -0.6585]],

        [[-0.2598, 

tensor([[ 1.0652,  1.8945, -0.2611, -0.3005,  1.4643],
        [ 0.4498,  0.1772,  1.0757,  0.1302,  0.5626],
        [-0.1850,  0.1699, -1.4455,  1.4274, -1.0439],
        [-0.2598,  1.4770, -0.7065,  0.2269, -0.4006]])

In [12]:
# Neural Network
from torch import nn

nn.Linear(10, 10)
nn.Conv1d(16, 32, 3, 1, 1)
nn.Conv2d(16, 32, 3, 1, 1)
nn.Conv3d(16, 32, 3, 1, 1)

nn.MaxPool2d(2, 2)
nn.AvgPool2d(2, 2)
nn.AdaptiveAvgPool2d((1, 1))

# Normalization
nn.BatchNorm1d(20)
nn.BatchNorm2d(20)
nn.LayerNorm(20)
nn.GroupNorm(8, 64)
nn.InstanceNorm2d(64)

nn.Embedding(1000, 128)
nn.LSTM(10, 20, 2)

nn.TransformerEncoderLayer(128, 4, 128)
nn.MultiheadAttention(128, 4)

nn.Sequential(
    nn.Linear(10, 20),
    nn.ReLU(),
    nn.Linear(20, 1)
)

nn.ModuleList([nn.Linear(10, 10) for _ in range(5)])
nn.ModuleDict({'linear': nn.Linear(10, 10), 'relu': nn.ReLU()})

ModuleDict(
  (linear): Linear(in_features=10, out_features=10, bias=True)
  (relu): ReLU()
)

In [24]:
# loss
loss = nn.MSELoss()
nn.BCELoss()
nn.CrossEntropyLoss()
nn.NLLLoss()
nn.PoissonNLLLoss()
nn.GaussianNLLLoss()
nn.KLDivLoss()
nn.CosineEmbeddingLoss()



CosineEmbeddingLoss()

In [22]:
# optimizer
model = nn.Linear(10, 1)

import torch.optim as optim
optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999))
optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
optim.RMSprop(model.parameters(), lr=0.001)
optim.Adagrad(model.parameters(), lr=0.001)

Adagrad (
Parameter Group 0
    differentiable: False
    eps: 1e-10
    foreach: None
    fused: None
    initial_accumulator_value: 0
    lr: 0.001
    lr_decay: 0
    maximize: False
    weight_decay: 0
)

In [ ]:
# lr
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

AttributeError: 'MSELoss' object has no attribute 'backward'

In [ ]:
# 开启梯度
x = torch.randn(2, 3, requires_grad=True)
y = x ** 2
z = y.mean()
z.backward()  # 反向传播
x.grad  # 查看梯度

x.grad.zero_()
# torch.autograd.grad(z, x)

with torch.no_grad():  # 禁用梯度计算
    y = x * 2

with torch.set_grad_enabled(False):  # 禁用梯度计算
    y = x * 2

x.detach()
x.requires_grad_(False)

# 梯度裁剪
torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

RuntimeError: Expected !nested_tensorlist[0].empty() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

In [46]:
# init
w = torch.empty(3, 5)
nn.init.uniform_(w, a=0, b=1)
nn.init.normal_(w, mean=0, std=1)
nn.init.constant_(w, 0.5)
nn.init.xavier_uniform_(w)  # Xavier 初始化
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')  # He 初始化
nn.init.orthogonal_(w)  # 正交初始化

tensor([[ 0.1379,  0.6082,  0.6019,  0.0910,  0.4903],
        [ 0.1235,  0.7619, -0.3717, -0.0589, -0.5125],
        [ 0.3117,  0.0330, -0.5837,  0.5738,  0.4815]])

In [48]:
# 广播规则：从右往左比较维度，维度相等或其中一个为1则可以广播
x = torch.randn(3, 1, 5)
y = torch.randn(1, 4, 5)
z = x + y  # 结果: [3, 4, 5]
print(z)


tensor([[[-1.5763,  0.2137, -0.0408, -0.9574, -1.9224],
         [ 0.0907, -0.5304, -0.1101, -1.0877, -1.7759],
         [-0.1896, -2.2964, -2.0669,  0.3943, -1.8009],
         [ 1.6133, -0.5444, -0.1867,  0.3827, -1.2904]],

        [[-1.3610, -0.2035, -0.4029, -3.5387, -0.9285],
         [ 0.3060, -0.9476, -0.4722, -3.6690, -0.7820],
         [ 0.0257, -2.7137, -2.4290, -2.1870, -0.8070],
         [ 1.8286, -0.9617, -0.5488, -2.1986, -0.2965]],

        [[ 0.7474,  0.5435,  0.1603, -1.0483, -2.0233],
         [ 2.4143, -0.2006,  0.0911, -1.1786, -1.8769],
         [ 2.1340, -1.9666, -1.8658,  0.3034, -1.9018],
         [ 3.9369, -0.2146,  0.0144,  0.2919, -1.3913]]])
